# Generated by Django 4.1.12 on 2023-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_remove_annotation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='text_selected',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
